### ISSUE TITLE
Consider chronoboost in build times

### ISSUE THREAD

**Issue by StoicLoofah** [StoicLoofah/spawningtool#25]
For units (not including warped units), we get the "born" time in trackerevents, which we subtract the build time from to get the start for the build order. Unfortunately, this doesn't always work because chronoboost speeds up that build time. 

In the opposite direction, Contaminate also isn't considered. Supply blocks also aren't considered.

This is a long-standing problem that I haven't addressed.

**Comment by StoicLoofah** [comment]
https://github.com/StoicLoofah/spawningtool/tree/feature-25-chronoboost

v1 is put together. I want to test this with the HotS data first before going through and changing all of the LotV data as well

**Comment by StoicLoofah** [comment]
5617c294a88437b906c3de624b82fecf66ba1a26 merged in

**Comment by EHadoux** [comment]
Hi Kevin, you may consider to have a look at https://github.com/MakozFriends/sc2reader/blob/plugin/chronobooststracker/sc2reader/engine/plugins/chronoboost.py
It may or may not give you some ideas to improve your code.
Especially that you can access ```event.target.location``` to exactly know which target it is.

**Comment by StoicLoofah** [comment]
@EHadoux thanks for the reference. I saw that you can get the location of the target, but for the `UnitBornEvent`, it also only has a location spawned and not the building that it came out of. I considered adding logic for finding the nearest building but then got lazy about it. especially because `UpgradeCompleteEvent` doesn't have a location on it. I would have needed fuzzy logic there anyways, so I got lazy with the whole business. Hopefully it works well enough :smile:

**Comment by EHadoux** [comment]
Brace yourself, CB have been removed in LotV :)

**Comment by dsjoerg** [comment]
omfg

**Comment by StoicLoofah** [comment]
Haha, I know, right? It feels like I just built this, too =P

To be honest, I'm more annoyed about them changing the timings. To date, I still haven't gotten a good solution to deal with when they patch and change build times, since that shows up in the data packs. Alas.
