### ISSUE TITLE
Can't install from Pypi using pip

### ISSUE THREAD

**Issue by Gusgus01** [StoicLoofah/spawningtool#44]
I receive the error "FileNotFoundError: [Errno 2] No such file or directory: 'README.md'" when installing from pip using pip install spawningtool.

This is because the sdist does not include README.md and CHANGELOG.md, so it can't build when it's pulled from Pypi. This could be fixed in a few ways. You could build a bdist_wheel as well which should be preferred in newer versions of pip. You could also create a MANIFEST.in which includes the two files.

**Comment by Gusgus01** [comment]
Created a pull request to address this issue, however, as I said, I think you could just build bdist_wheel and upload that to Pypi as a solution. 

https://github.com/StoicLoofah/spawningtool/pull/45

**Comment by StoicLoofah** [comment]
Just shipped 2.2.1, which appears to work for me. Does it work for you?

**Comment by Gusgus01** [comment]
Yep, works from pip now. Thanks!
