### ISSUE TITLE
Spawning tool freezes. Is there a way to reset spawning tool?

### ISSUE THREAD

**Issue by jacobkim9881** [StoicLoofah/spawningtool#59]
Thanks for making spawning tool. Somehow my spawning tool freezes suddenly like below,

![spawningtool-bug](https://user-images.githubusercontent.com/46774300/152711008-68138f2f-cce3-414d-8c10-b4a9b3a003a5.PNG)

I tried to reinstall spawning tool and overwolf but it doesn't restart spawning tool but shows same screen above. 

Is there a place where spawning tool's settings or any environment is placed on Windows? If there are then I want to reset such environments. Or if any tips I would be happy to hear.

**Comment by StoicLoofah** [comment]
Thanks for using the app and reporting this issue.

I just released v1.10.2 that should fix this. The problem is that I hadn't updated the app in awhile, and I was using a API function that was just fully deprecated. Try again after the app is fully updated

**Comment by jacobkim9881** [comment]
@StoicLoofah So spawning tool was freezed because API function didn't work. Now spawning tool works well :)
